version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '8081:8080'
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: payments
