version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres-database
  postgres-database:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root